version: '3'

services:
  node:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - MONGO_URI=mongodb://mongodb:27017/myapp
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    networks:
      - app-network

    
  mongodb:
    image: mongo:6
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    command: mongod --bind_ip_all

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: